# Generated by Django 4.1.2 on 2022-11-19 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cut",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cutting_day", models.DateField(unique=True)),
                ("cutting_hour", models.TimeField(unique=True)),
            ],
        ),
    ]
